### PR TITLE
Deprecate multitude of singleton thread-local resource, use ScopedThreadLocal instead.

### LINKED ISSUE #683: deepCopy fails when copying DTOs with @AsMarshallable dynamic enum fields
It results in an invalid re-use pattern of the shared `Wires.acquireBinaryWire()`

### PR DESCRIPTION
**Pull request by nicktindall**
Depends on OpenHFT/Chronicle-Core#576

Fixes #683

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/wire/WireMarshaller.java [hunk 1]
```diff
@@ -1211,12 +1216,14 @@ protected void setValue(Object o, @NotNull ValueIn read, boolean overwrite) {
...
-            byte[] decode = Base64.getDecoder().decode(s);
-            bytes.clear();
-            bytes.write(decode);
+            try (ScopedResource<StringBuilder> stlSb = Wires.acquireStringBuilderScoped()) {
+                @NotNull StringBuilder sb0 = stlSb.get();
+                read.text(sb0);
+                String s = WireInternal.INTERNER.intern(sb0);
+                byte[] decode = Base64.getDecoder().decode(s);
+                bytes.clear();
+                bytes.write(decode);
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/wire/WireMarshaller.java:1246]: I wonder how often interning works with arbitrary base64 strings, do we not have a utility to decode base64 directly from a StringBuilder?

File: src/main/java/net/openhft/chronicle/wire/Wires.java [hunk 2]
```diff
@@ -1055,15 +1122,17 @@ enum SerializeBytes implements Function<Class, SerializationStrategy> {
...
+                @NotNull StringBuilder sb0 = stlSb.get();
+                in.text(sb0);
+                String s = WireInternal.INTERNER.intern(sb0);
+                byte[] decode = Base64.getDecoder().decode(s);
+                if (o == null)
+                    return Bytes.wrapForRead(decode);
+                o.clear();
+                o.write(decode);
+                return o;
+            }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/wire/Wires.java:1143]: again it'd be great to be able to base64 decode directly from a string builder

**Review by JerryShea — APPROVED** [review]
